python3 main.py --model ppnv2 --parameters label_file=/home/zenglh/activitynet/activitynet_caption2.json,visual_file=/home/zenglh/activitynet/activitynet_c3d.hdf5,language_file=/home/zenglh/activitynet/activitynet_bert2.hdf5,output=/home/zenglh/DenseCap/results,train_steps=60000,decay_steps=20000,eval_steps=500,hidden_size=256,filter_size=256,anchor_layers=7,num_mab=1,gpu=1

python3 main.py --model ppnv2 --parameters label_file=/home/zenglh/activitynet/activitynet_caption2.json,visual_file=/home/zenglh/activitynet/activitynet_c3d.hdf5,language_file=/home/zenglh/activitynet/activitynet_bert2.hdf5,output=/home/zenglh/DenseCap/results,train_steps=60000,decay_steps=20000,eval_steps=500,hidden_size=256,filter_size=256,anchor_layers=7,num_mab=2,gpu=1

python3 main.py --model ppnv2 --parameters label_file=/home/zenglh/activitynet/activitynet_caption2.json,visual_file=/home/zenglh/activitynet/activitynet_c3d.hdf5,language_file=/home/zenglh/activitynet/activitynet_bert2.hdf5,output=/home/zenglh/DenseCap/results,train_steps=60000,decay_steps=20000,eval_steps=500,hidden_size=256,filter_size=256,anchor_layers=7,num_mab=4,gpu=1

python3 main.py --model ppnv2 --parameters label_file=/home/zenglh/activitynet/activitynet_caption2.json,visual_file=/home/zenglh/activitynet/activitynet_c3d.hdf5,language_file=/home/zenglh/activitynet/activitynet_bert2.hdf5,output=/home/zenglh/DenseCap/results,train_steps=60000,decay_steps=20000,eval_steps=500,hidden_size=256,filter_size=256,anchor_layers=7,num_mab=5,gpu=1

python3 main.py --model ppnv2 --parameters label_file=/home/zenglh/activitynet/activitynet_caption2.json,visual_file=/home/zenglh/activitynet/activitynet_c3d.hdf5,language_file=/home/zenglh/activitynet/activitynet_bert2.hdf5,output=/home/zenglh/DenseCap/results,train_steps=60000,decay_steps=20000,eval_steps=500,hidden_size=256,filter_size=256,anchor_layers=5,num_mab=3,gpu=1

python3 main.py --model ppnv2 --parameters label_file=/home/zenglh/activitynet/activitynet_caption2.json,visual_file=/home/zenglh/activitynet/activitynet_c3d.hdf5,language_file=/home/zenglh/activitynet/activitynet_bert2.hdf5,output=/home/zenglh/DenseCap/results,train_steps=60000,decay_steps=20000,eval_steps=500,hidden_size=256,filter_size=256,anchor_layers=6,num_mab=3,gpu=1

python3 main.py --model ppnv2 --parameters label_file=/home/zenglh/activitynet/activitynet_caption2.json,visual_file=/home/zenglh/activitynet/activitynet_c3d.hdf5,language_file=/home/zenglh/activitynet/activitynet_bert2.hdf5,output=/home/zenglh/DenseCap/results,train_steps=60000,decay_steps=20000,eval_steps=500,hidden_size=256,filter_size=256,anchor_layers=8,num_mab=3,gpu=1

python3 main.py --model ppnv2 --parameters label_file=/home/zenglh/activitynet/activitynet_caption2.json,visual_file=/home/zenglh/activitynet/activitynet_c3d.hdf5,language_file=/home/zenglh/activitynet/activitynet_bert2.hdf5,output=/home/zenglh/DenseCap/results,train_steps=60000,decay_steps=20000,eval_steps=500,hidden_size=256,filter_size=256,anchor_layers=9,num_mab=3,gpu=1